blueprint:
  name: Device Monitoring Notification (Robust v2)
  description: >
    Extrem robuster Blueprint zur Überwachung von Geräten wie Waschmaschine,
    Trockner oder Geschirrspüler. Erkennt Start und Ende zuverlässig – auch bei
    schnellen Neustarts, Sensor-Sprüngen und Home-Assistant-Neustarts.
    Nutzt eine interne Statusmaschine (input_select).

  domain: automation

  input:
    power_sensor:
      name: Leistungssensor
      selector:
        entity:
          domain: sensor

    status_helper:
      name: Status-Helfer (input_select)
      description: Muss die Optionen idle, running, finished enthalten.
      selector:
        entity:
          domain: input_select

    start_threshold:
      name: Start-Schwelle (Watt)
      default: 8
      selector:
        number:
          min: 1
          max: 200
          step: 1
          unit_of_measurement: W

    start_duration:
      name: Start-Hysterese (Minuten)
      default: 2
      selector:
        number:
          min: 0.25
          max: 10
          step: 0.25
          unit_of_measurement: min

    finish_threshold:
      name: Fertig-Schwelle (Watt)
      default: 5
      selector:
        number:
          min: 1
          max: 200
          step: 1
          unit_of_measurement: W

    finish_duration:
      name: Fertig-Hysterese (Minuten)
      default: 3
      selector:
        number:
          min: 0.25
          max: 10
          step: 0.25
          unit_of_measurement: min

    start_actions:
      name: Aktionen bei Start
      default: []
      selector:
        action: {}

    finish_actions:
      name: Aktionen bei Fertig
      default: []
      selector:
        action: {}

trigger:
  - platform: homeassistant
    event: start
    id: ha_start

  - platform: numeric_state
    entity_id: !input power_sensor
    above: !input start_threshold
    for:
      minutes: !input start_duration
    id: start_detected

variables:
  status: !input status_helper
  power: !input power_sensor

action:
  - choose:

      # ---------------------------------------------------------
      # HA Neustart: Status rekonstruieren
      # ---------------------------------------------------------
      - conditions:
          - condition: trigger
            id: ha_start
        sequence:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input power_sensor
                    above: !input start_threshold
                sequence:
                  - service: input_select.select_option
                    target: { entity_id: !input status_helper }
                    data: { option: running }

              - conditions:
                  - condition: numeric_state
                    entity_id: !input power_sensor
                    below: !input finish_threshold
                sequence:
                  - service: input_select.select_option
                    target: { entity_id: !input status_helper }
                    data: { option: finished }

            default:
              - service: input_select.select_option
                target: { entity_id: !input status_helper }
                data: { option: idle }

      # ---------------------------------------------------------
      # Start erkannt → Status setzen + Start-Aktionen
      # ---------------------------------------------------------
      - conditions:
          - condition: trigger
            id: start_detected
          - condition: state
            entity_id: !input status_helper
            state: idle
        sequence:
          - service: input_select.select_option
            target: { entity_id: !input status_helper }
            data: { option: running }

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (start_actions | length) > 0 }}"
                sequence: !input start_actions

          # -----------------------------------------------------
          # Jetzt robust auf das Ende warten (wie Original)
          # -----------------------------------------------------
          - wait_for_trigger:
              - platform: numeric_state
                entity_id: !input power_sensor
                below: !input finish_threshold
                for:
                  minutes: !input finish_duration

          # -----------------------------------------------------
          # Fertig erkannt → Status setzen + Aktionen
          # -----------------------------------------------------
          - service: input_select.select_option
            target: { entity_id: !input status_helper }
            data: { option: finished }

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (finish_actions | length) > 0 }}"
                sequence: !input finish_actions

          # Automatisch zurück auf idle nach 2 Minuten
          - delay: "00:02:00"
          - service: input_select.select_option
            target: { entity_id: !input status_helper }
            data: { option: idle }

mode: restart
